all_raw_data_path: '/projects/fmba_covid/publication'
fmba_raw_path: '/projects/fmba_covid/publication/fmba'
adaptive_raw_path: '/projects/fmba_covid/publication/adaptive_new'
hip_raw_path: '/projects/fmba_covid/publication/hip_full'
fmba_desc_joint: 'data/preprocessed_fmba_metadata_joint.csv'
fmba_desc_alpha: 'data/preprocessed_fmba_metadata_alpha.csv'
fmba_desc_beta: 'data/preprocessed_fmba_metadata_beta.csv'
hip_desc: 'data/hip_full.csv'
adaptive_desc: 'data/adaptive_new.csv'
allele_names: ['A*02', 'A*01', 'A*03', 'A*24', 'B*07', 'B*35', 'B*44', 'B*18', 'C*07', 'C*04', 'C*12', 'DQB1*05', 'DRB1*16']
#allele_names: ['A*02',
#               'A*03',
#               'A*01',
#               'A*25',
#               'A*24',
#               'A*11',
#               'A*23',
#               'A*32',
#               'A*26',
#               'A*29',
#               'A*68',
#               'A*66',
#               'A*30',
#               'A*31',
#               'A*33',
#               'A*69',
#               'B*35',
#               'B*18',
#               'B*13',
#               'B*40',
#               'B*07',
#               'B*37',
#               'B*08',
#               'B*15',
#               'B*27',
#               'B*51',
#               'B*14',
#               'B*44',
#               'B*50',
#               'B*49',
#               'B*41',
#               'B*58',
#               'B*39',
#               'B*45',
#               'B*38',
#               'B*52',
#               'B*56',
#               'B*57',
#               'B*48',
#               'B*47',
#               'B*53',
#               'B*55',
#               'B*46',
#               'B*54',
#               'B*42',
#               'B*73',
#               'C*04',
#               'C*06',
#               'C*03',
#               'C*07',
#               'C*02',
#               'C*12',
#               'C*01',
#               'C*05',
#               'C*08',
#               'C*15',
#               'C*17',
#               'C*16',
#               'C*14',
#               'DPB1*02',
#               'DPB1*04',
#               'DPB1*03',
#               'DPB1*06',
#               'DPB1*01',
#               'DPB1*104',
#               'DPB1*13',
#               'DPB1*05',
#               'DPB1*11',
#               'DPB1*09',
#               'DPB1*350',
#               'DPB1*23',
#               'DPB1*19',
#               'DPB1*126',
#               'DPB1*124',
#               'DPB1*10',
#               'DPB1*34',
#               'DPB1*105',
#               'DPB1*17',
#               'DPB1*14',
#               'DPB1*136',
#               'DPB1*266',
#               'DPB1*15',
#               'DPB1*484',
#               'DPB1*16',
#               'DPB1*36',
#               'DPB1*88',
#               'DPB1*26',
#               'DPB1*20',
#               'DPB1*47',
#               'DPB1*414',
#               'DPB1*138',
#               'DQB1*03',
#               'DQB1*05',
#               'DQB1*02',
#               'DQB1*06',
#               'DQB1*04',
#               'DRB1*11',
#               'DRB1*01',
#               'DRB1*07',
#               'DRB1*08',
#               'DRB1*03',
#               'DRB1*15',
#               'DRB1*13',
#               'DRB1*04',
#               'DRB1*09',
#               'DRB1*10',
#               'DRB1*14',
#               'DRB1*12',
#               'DRB1*16']