all_raw_data_path: '/projects/fmba_covid/publication'
fmba_raw_path: '/projects/fmba_covid/publication/fmba'
adaptive_raw_path: '/projects/fmba_covid/publication/adaptive_new'
hip_raw_path: '/projects/fmba_covid/publication/hip_full'
fmba_desc: 'data/preprocessed_fmba_metadata.csv'
hip_desc: 'data/hip_full.csv'
adaptive_desc: 'data/adaptive_new.csv'
allele_names: ['A*02', 'A*01', 'A*03', 'A*24', 'B*07', 'B*35', 'B*44', 'B*18', 'C*07', 'C*04', 'C*12', 'DQB1*05', 'DRB1*16']